### ISSUE TITLE
Rotate image on right click fails if more than 12 dashboard windows

### ISSUE THREAD

**Issue by crow983** [VA3HDL/hamdashboard#46]
Rotating a dashboard windows through multiple images by right clicking only works on the first 12 frames.  Fails on frames 13 and greater.

**Comment by VA3HDL** [comment]
Is it fixed now? If not, could you please attach your config.js so I can debug the issue? Thanks.

**Comment by VA3HDL** [comment]
The config.js file you sent is missing an important part. The delays in milliseconds to rotate the contents of the tiles.

I've added this at the end of your config.js file and I get it show and images rotate without any issues

const tileDelay =
    [60000, 60000, 60000, 60000, 60000,
   60000, 60000, 60000, 60000, 60000,
   60000, 60000, 60000, 60000, 60000,
   60000, 60000, 60000, 60000, 60000,
    ];

Add the above and try again.

Thanks.

**Comment by crow983** [comment]
Sorry, I must be missing something.

I have added it, but it still doesn't rotate past the 12th window for me.  Specifically, 3rd row, image 3 and 4.  And, 4th row, image 1 should all rotate.

I have tried this on Chrome, Brave, Edge and Firefox.  

Thanks again
[config.zip](https://github.com/user-attachments/files/18417909/config.zip)

**Comment by VA3HDL** [comment]
There is nothing wrong with the last config file you shared. I see that you added the delays.
The images rotate automatically every 60 seconds (or 60000 milliseconds as specified on the variable you added.)
The images also rotate with the mouse right clicking over them.
Please use F12 and send an screenshot of the console to see if you getting some error that I'm not getting here.

**Comment by crow983** [comment]
Here is a screenshot.  Let me know what else you'd like.  Thx!
![Capture](https://github.com/user-attachments/assets/7a98eb84-7b65-46b8-805f-ab6fdeb65c34)

**Comment by VA3HDL** [comment]
There is nothing unusual on the console. The first two errors seems unrelated to the dashboard. Did you right click on any tile above 12?
I tried the one with the space weather and is working fine.

**Comment by crow983** [comment]
Thank you for all your help.  It still doesn't work on any tiles above #12.  When I right click on the space weather tile (#16), it does not rotate.

I'm using Chrome 132.0.6834.84.  I don't have any extensions installed.

Don't spend any more time on it.  I will just make sure that any tiles I need to rotate are in the first 12 slots :-)

Thank you for trying.

-Richard
